# Generated by Django 4.2.1 on 2023-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
