# Generated by Django 4.2.1 on 2023-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_vulnerability_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMonitorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
