# Generated by Django 4.2.1 on 2023-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='ips_monitorization',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
